name: CI

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  code-style:
    name: Code style
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref }}

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Check code style
        run: ./gradlew ktlintCheck

  tests:
    name: Tests
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref }}

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Run tests
        run: ./gradlew allTests

      - name: Display unit test results
        uses: mikepenz/action-junit-report@v4
        if: always()
        with:
          check_name: 'Tests results'
          report_paths: '**/build/test-results/**/TEST-*.xml'
